### PR TITLE
Initial overworld setup

### PR DESCRIPTION
**Pull request by guimcaballero**
This PR adds the basis for the Overworld section of the game. Adds a small plane, WASD movement, and mouse rotation.

I expect this code to be completely removed/changed in the future, I just wanted to get the ball going. Hardcoding + Magic numbers galore. 

https://user-images.githubusercontent.com/29580620/107891122-fed3e880-6f1c-11eb-902f-00cd0219686b.mov

### CODE REVIEW

**Comment by inodentry** [comment]
I think we shouldn't have it as a `Plugin`. I don't think enforcing modularity/structure this early on in the project is a great idea. It's going to constrain development if we try to fit everything into some well-defined set of plugins.

After this is merged, I'd want to set up Bevy `State`s for the overall app state. Having things as granular plugins already adds a bunch of cognitive overhead and makes doing that difficult.

**Comment by inodentry** [comment]
I vote to merge this, as the goal is to get started.

We can fix the issues with it in subsequent PRs.

Let's have someone else give a thumbs up before pushing the green button, though.

**Comment by inodentry** [comment]
One of the next things to focus on would be decoupling the player and the camera. Parenting the camera under the player entity is never a good idea in game dev. :laughing:

**Comment by guimcaballero** [comment]
> One of the next things to focus on would be decoupling the player and the camera.

Good idea. I just went for the easiest route possible for now.

**Comment by inodentry** [comment]
Actually, I think I can't do any harm by just merging this right now, as we know what to do next.

**Pull request merged**
